// swift-tools-version: 6.0
// Distribution manifest for github.com/extentos/swift-glasses — GENERATED by
// ios-library/publish/stage-swift-glasses.sh in the Extentos monorepo (the
// source of truth). Do not edit in the distribution repo; changes belong in
// the monorepo's ios-library/publish/Package.swift.template.
import PackageDescription

let package = Package(
    name: "Extentos",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "GlassesCore", targets: ["GlassesCore"]),
        .library(name: "GlassesUI", targets: ["GlassesUI"]),
        .library(name: "GlassesDebug", targets: ["GlassesDebug"]),
        .library(name: "GlassesLifecycle", targets: ["GlassesLifecycle"]),
        .library(name: "GlassesTesting", targets: ["GlassesTesting"]),
    ],
    dependencies: [
        .package(url: "https://github.com/facebook/meta-wearables-dat-ios", from: "0.8.0"),
    ],
    targets: [
        // Shared Rust core, compiled per-platform and shipped as a binary
        // xcframework on the matching GitHub Release (device arm64 + a
        // universal arm64/x86_64 simulator slice + macOS arm64).
        .binaryTarget(
            name: "extentos_coreFFI",
            url: "https://github.com/extentos/swift-glasses/releases/download/1.8.0/extentos_coreFFI.xcframework.zip",
            checksum: "60e335e21b52570cc99a0643edbac78ebdae61771508894bfddda93fd2d9d42e"
        ),
        .target(
            name: "GlassesCore",
            dependencies: [
                "extentos_coreFFI",
                .product(name: "MWDATCore", package: "meta-wearables-dat-ios"),
                .product(name: "MWDATCamera", package: "meta-wearables-dat-ios"),
            ],
            // uniffi 0.28's generated Swift uses a nonisolated global `var`
            // that Swift 6 strict concurrency rejects; the bindings compile in
            // Swift 5 language mode (tracked monorepo follow-up, no API impact).
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .target(name: "GlassesUI", dependencies: ["GlassesCore"]),
        .target(name: "GlassesDebug", dependencies: ["GlassesCore"]),
        .target(name: "GlassesLifecycle", dependencies: ["GlassesCore"]),
        .target(name: "GlassesTesting", dependencies: ["GlassesCore"]),
    ]
)
