// swift-tools-version: 6.0
// Distribution manifest for github.com/extentos/swift-glasses — GENERATED by
// ios-library/publish/stage-swift-glasses.sh in the Extentos monorepo (the
// source of truth). Do not edit in the distribution repo; changes belong in
// the monorepo's ios-library/publish/Package.swift.template.
import PackageDescription

let package = Package(
    name: "Extentos",
    // iOS 17 / macOS 14 because GlassesLocal pulls mlx-swift-lm, which declares
    // those minimums, and SPM applies platform floors PACKAGE-WIDE — there is
    // no way to keep one product at iOS 16 and ship another that needs 17.
    // Raised from iOS 16 / macOS 13 when the local tier joined distribution.
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "GlassesCore", targets: ["GlassesCore"]),
        .library(name: "GlassesUI", targets: ["GlassesUI"]),
        .library(name: "GlassesDebug", targets: ["GlassesDebug"]),
        .library(name: "GlassesLifecycle", targets: ["GlassesLifecycle"]),
        .library(name: "GlassesTesting", targets: ["GlassesTesting"]),
        // The on-device local tier (MLX brain) — what makes `local-*` models
        // actually run on the phone rather than falling through to the cloud.
        // A SEPARATE product so apps that don't opt in never link MLX/Metal:
        // unlike an Android AAR, SPM only builds what you import, so the cost
        // of shipping it here is the platform floor above, not binary weight.
        .library(name: "GlassesLocal", targets: ["GlassesLocal"]),
        // The on-device neural voice (Kokoro via sherpa-onnx). Separate for
        // the same reason as GlassesLocal: the sherpa + onnxruntime binaries
        // only land on apps that opt into the voice.
        .library(name: "GlassesLocalVoice", targets: ["GlassesLocalVoice"]),
    ],
    dependencies: [
        .package(url: "https://github.com/facebook/meta-wearables-dat-ios", from: "0.8.0"),
        // MLX model serving for the on-device local tier (Apple platforms only).
        .package(url: "https://github.com/ml-explore/mlx-swift-lm.git", from: "3.31.4"),
        // The #hubDownloader / #huggingFaceTokenizerLoader macros expand to
        // HubClient / Tokenizers code the CONSUMER must import (mlx-swift-lm
        // integrates by protocol, not by dependency).
        .package(url: "https://github.com/huggingface/swift-huggingface.git", from: "0.1.0"),
        .package(url: "https://github.com/huggingface/swift-transformers.git", from: "1.0.0"),
    ],
    targets: [
        // Shared Rust core, compiled per-platform and shipped as a binary
        // xcframework on the matching GitHub Release (device arm64 + a
        // universal arm64/x86_64 simulator slice + macOS arm64).
        .binaryTarget(
            name: "extentos_coreFFI",
            url: "https://github.com/extentos/swift-glasses/releases/download/2.1.0/extentos_coreFFI.xcframework.zip",
            checksum: "310ab876fdf466f24f584919a210c284c97f999e44dc6acd1ba6c6d29b9d6b12"
        ),
        .target(
            name: "GlassesCore",
            dependencies: [
                "extentos_coreFFI",
                .product(name: "MWDATCore", package: "meta-wearables-dat-ios"),
                .product(name: "MWDATCamera", package: "meta-wearables-dat-ios"),
            ],
            // uniffi 0.28's generated Swift uses a nonisolated global `var`
            // that Swift 6 strict concurrency rejects; the bindings compile in
            // Swift 5 language mode (tracked monorepo follow-up, no API impact).
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .target(name: "GlassesUI", dependencies: ["GlassesCore"]),
        .target(name: "GlassesDebug", dependencies: ["GlassesCore"]),
        .target(name: "GlassesLifecycle", dependencies: ["GlassesCore"]),
        .target(name: "GlassesTesting", dependencies: ["GlassesCore"]),
        .target(
            name: "GlassesLocal",
            dependencies: [
                "GlassesCore",
                .product(name: "MLXLLM", package: "mlx-swift-lm"),
                .product(name: "MLXLMCommon", package: "mlx-swift-lm"),
                .product(name: "MLXHuggingFace", package: "mlx-swift-lm"),
                .product(name: "HuggingFace", package: "swift-huggingface"),
                .product(name: "Tokenizers", package: "swift-transformers"),
            ],
            // Swift 5 language mode like GlassesCore: MLX's UserInput/Chat
            // types are not Sendable-annotated yet.
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        // sherpa-onnx C API shim (pinned v1.13.4). The committed header rides
        // this target; the static libraries are the two binary targets below.
        .target(name: "SherpaOnnxC"),
        // Both are Release ASSETS rather than local paths — a published
        // package cannot carry local-path binaryTargets, which is precisely
        // why the voice shipped on Android months before iOS.
        .binaryTarget(
            name: "sherpaOnnxFFI",
            url: "https://github.com/extentos/swift-glasses/releases/download/2.1.0/sherpaOnnxFFI.xcframework.zip",
            checksum: "f5a5719bb7618008a8c00c40d9d8f6dd0693794da080c48999ab4735f51b9652"
        ),
        .binaryTarget(
            name: "onnxruntimeFFI",
            url: "https://github.com/extentos/swift-glasses/releases/download/2.1.0/onnxruntimeFFI.xcframework.zip",
            checksum: "601f299841b37a242fe20fd8d429a993ec63137fcb5bd93c3b465d5c125c75fd"
        ),
        .target(
            name: "GlassesLocalVoice",
            dependencies: ["GlassesCore", "SherpaOnnxC", "sherpaOnnxFFI", "onnxruntimeFFI"],
            // Swift 5 language mode like GlassesCore/GlassesLocal: the C
            // interop layer predates strict concurrency.
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
    ]
)
